### ISSUE TITLE
Support `callr::rscript()` or `callr:r()`

### ISSUE THREAD

**Issue by gadenbuie** [MilesMcBain/capsule#25]
I've been using (and enjoying!) capsule to write scripts to run in GHA workflows. One minor point of friction is missing the ability to call a capsule-managed `callr::rscript()`.

One option would be a new function, e.g. `run_callr_rscript` that calls `callr:rscript()` instead of `callr::r()`.

An alternative that's either clever or more ergonomic would be to dispatch to `callr::rscript()` if `run_callr()` receives a character string input:

```r
run_callr <- function(x, ...) {
  reproduce_lib_if_not_present()
  UseMethod("run_callr", x)
}

run_callr.character <- function(x, ...) {
  callr::rscript(x, libpath = c(renv::paths$library()), show = TRUE, ...)
}

run_callr.function <- function(x, ...) {
  callr::r(x, libpath = c(renv::paths$library()), show = TRUE, ...)
}
```

Happy to submit a PR for either approach 😄

**Comment by MilesMcBain** [comment]
Ah thanks, I can see why this would be useful!

I think I prefer a new function, possibly just `run_rscript`.

Would you ever want to pass the path of some file containing the script text, rather than the text itself?

**Comment by gadenbuie** [comment]
Nice, `run_rscript` is clear enough!

> Would you ever want to pass the path of some file containing the script text, rather than the text itself?

Yeah I should have been more explicit. It'd always be the path to the script. (If we were using S3 we'd have to dispatch on character input.) It'd be equivalent to running a script via `Rscript` inside the capsule.
